### ISSUE TITLE
Plotting error with TF motif NKX2-1_M08973

### ISSUE THREAD

**Issue by daramirez** [Dowell-Lab/TFEA#4] opened 2019-12-23 04:52 UTC
Hello,

TFEA is encountering an issue when I add the options "--output_type html" and "--plotall". I can use TFEA when I do not add these flags. I am attaching here the error log that I get. I could not figure out what is happening with that particular plotting of motif NKX2-1_M08973. I hope that you can help me. 

Thank you.

[20191222_TFEA_error_log.txt](https://github.com/Dowell-Lab/TFEA/files/3993668/20191222_TFEA_error_log.txt)

**Comment by jdrubin91** [comment] 2019-12-23 05:54
Hey Daniel,

I do not have easy access to my computer right now but that error seems to be an issue with generating the motif logo for display. To do this TFEA first uses a meme subroutine to convert a .meme formatted database file to an .eps file. Then, it uses imagemagick to convert eps to png (for html display). It seems like it is having trouble locating the appropriate eps file. The relevant portion of that error file is this:

TFEA.exceptions.SubprocessError: convert: unable to open image `/Shares/CL_Shared/data/daniel/PRO-seq_primates-perturbations/Nascent-Flow/Human/tfea/plots/logoNKX2-1_M08973_1.eps': No such file or directory @

I would first check your meme installation (try running meme2images on your command line). It seems like imagemagick is installed. If that doesnt work then this will have to wait until after the holidays.

Good luck! Sorry about the bugs!

Best,
Jonathan

**Comment by daramirez** [comment] 2019-12-23 17:38
Thank you, Jon.
Meme seems to be installed okay as assessed by typing 'meme2images' and getting it recognized as a command. It was not clear to me what is it that I am supposed to try to make it work from what you responded, sorry...
I understand that this may had to wait until after the holidays. I just thought of leaving it here for documentation purposes.
Daniel

**Comment by jdrubin91** [comment] 2020-02-06 16:40
Hey Daniel,

I believe this error was caused by the dash ("-") present in that motif name. This seems to be a meme2images issue and I am not sure how/if I can fix it besides renaming the motifs within the .meme database file so none contain any dashes. For now, I've added a line to catch the exception thrown by this error so that it ignores it. This means that those motif logos will not be displayed in the output html but TFEA should still run other motifs. I am closing this issue for now and the other one you reported. Please don't hesitate to open up more issues if you run into problems!

Thanks!
Jonathan

**Closed by jdrubin91** 2020-02-06 16:40 UTC
